{
 "title": "App | Discord Dashboard",
 "tags": [
  "discord",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "guild", "label": "Guild", "query": { "query": "discord_messages_total" } },
   { "name": "member", "label": "Member", "query": { "query": "discord_messages_total" } },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Discord Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(discord_latency*1000)" }
   ]
  },
  {
   "title": "Total Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(discord_messages_total{guild=~\"$guild\"}) by (guild)",
     "legendFormat": "{{ guild }}"
    }
   ]
  },
  {
   "title": "Server Boost Status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(discord_boosts{guild=~\"$guild\"})",
     "legendFormat": "Server Boost Count"
    }
   ]
  },
  {
   "title": "Total Members",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(discord_members_registered{guild=~\"$guild\"} + discord_bots_registered{guild=~\"$guild\"})"
    }
   ]
  },
  {
   "title": "Message Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(discord_messages_total{guild=~\"$guild\"}[1m])) by (guild)",
     "legendFormat": "{{guild}}"
    }
   ]
  },
  {
   "title": "Humans",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(discord_members_registered{guild=~\"$guild\"})"
    }
   ]
  },
  {
   "title": "Bots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(discord_bots_registered{guild=~\"$guild\"})"
    }
   ]
  },
  {
   "title": "Online Members",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(discord_members_online{guild=~\"$guild\"})"
    }
   ]
  },
  {
   "title": "Messages by Top 25 Members",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " topk(25, sum(discord_messages_total{guild=~\"$guild\",member=~\"$member\"})by(member))",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Active Users (1d)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(changes(discord_messages_total{member=~\"$member\",guild=~\"$guild\"}[1d]) > 0) by (member))"
    }
   ]
  },
  {
   "title": "Reactions by Top 25 Members",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " topk(25, sum(discord_reactions_total{guild=~\"$guild\",member=~\"$member\"})by(member))",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Active Users (1w)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(changes(discord_messages_total{member=~\"$member\",guild=~\"$guild\"}[1w]) > 0) by (member))"
    }
   ]
  }
 ]
}